const $=id=>document.getElementById(id);const fileInput=$('fileInput'),dropzone=$('dropzone'),filePanel=$('filePanel'),preview=$('preview'),fitButton=$('fitButton'),status=$('status'),result=$('result'),canvas=$('canvas');let sourceFile=null,sourceImage=null,sourceUrl=null,downloadUrl=null;
const fmtBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(n<10240?1:0)} KB`:`${(n/1048576).toFixed(2)} MB`;
const mimeExt=m=>m==='image/png'?'png':m==='image/webp'?'webp':'jpg';
function setStatus(msg,error=false){status.textContent=msg;status.classList.toggle('error',error)}
function resetResult(){result.classList.add('hidden');if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null}}
function updateCropUI(){const enabled=$('coverCrop').checked&&$('width').value&&$('height').value&&sourceImage;$('cropControls').classList.toggle('hidden',!enabled);if(enabled){const w=parseInt($('width').value,10),h=parseInt($('height').value,10);$('cropPreview').style.aspectRatio=`${w}/${h}`;$('cropPreviewImg').style.objectPosition=`${$('cropX').value}% ${$('cropY').value}%`}}
async function loadFile(file){resetResult();setStatus('');if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)){setStatus('Usa una imagen JPG, PNG o WebP.',true);return}sourceFile=file;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);const img=new Image();img.decoding='async';img.src=sourceUrl;try{await img.decode()}catch{setStatus('No pudimos leer esta imagen.',true);return}sourceImage=img;preview.src=sourceUrl;$('cropPreviewImg').src=sourceUrl;$('fileName').textContent=file.name;$('fileDetails').textContent=`${fmtBytes(file.size)} · ${img.naturalWidth} × ${img.naturalHeight} px`;dropzone.classList.add('hidden');filePanel.classList.remove('hidden');fitButton.disabled=false;updateCropUI()}
fileInput.addEventListener('change',e=>loadFile(e.target.files[0]));$('changeFile').addEventListener('click',()=>fileInput.click());['dragenter','dragover'].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.classList.add('dragging')}));['dragleave','drop'].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.classList.remove('dragging')}));dropzone.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
['width','height'].forEach(id=>$(id).addEventListener('input',updateCropUI));$('coverCrop').addEventListener('change',updateCropUI);['cropX','cropY'].forEach(id=>$(id).addEventListener('input',updateCropUI));$('centerCrop').addEventListener('click',()=>{$('cropX').value=50;$('cropY').value=50;updateCropUI()});
function outputDimensions(){const sw=sourceImage.naturalWidth,sh=sourceImage.naturalHeight,w=parseInt($('width').value,10),h=parseInt($('height').value,10);if(w&&h)return[w,h];if(w)return[w,Math.max(1,Math.round(sh*w/sw))];if(h)return[Math.max(1,Math.round(sw*h/sh)),h];return[sw,sh]}
function drawImage(w,h){canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:true});ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const crop=$('coverCrop').checked&&$('width').value&&$('height').value;if(!crop){ctx.drawImage(sourceImage,0,0,w,h);return}const sw=sourceImage.naturalWidth,sh=sourceImage.naturalHeight,target=w/h,source=sw/sh;let sx=0,sy=0,sWidth=sw,sHeight=sh;if(source>target){sWidth=sh*target;const maxX=sw-sWidth;sx=maxX*(parseInt($('cropX').value,10)/100)}else{sHeight=sw/target;const maxY=sh-sHeight;sy=maxY*(parseInt($('cropY').value,10)/100)}ctx.drawImage(sourceImage,sx,sy,sWidth,sHeight,0,0,w,h)}
function blobAt(mime,quality){return new Promise(resolve=>canvas.toBlob(resolve,mime,quality))}
async function encodeUnderLimit(mime,maxBytes){if(mime==='image/png'){const blob=await blobAt(mime);return{blob,quality:null,met:!maxBytes||blob.size<=maxBytes}}if(!maxBytes){const blob=await blobAt(mime,.94);return{blob,quality:.94,met:true}}let low=.08,high=.98,best=null,bestQ=null;for(let i=0;i<11;i++){const q=(low+high)/2,blob=await blobAt(mime,q);if(!blob)break;if(blob.size<=maxBytes){best=blob;bestQ=q;low=q}else high=q}if(best)return{blob:best,quality:bestQ,met:true};const blob=await blobAt(mime,.04);return{blob,quality:.04,met:blob&&blob.size<=maxBytes}}
async function fit(){if(!sourceImage)return;fitButton.disabled=true;$('buttonText').textContent='Procesando…';setStatus('Buscando el mejor ajuste sin subir tu archivo…');resetResult();try{const mime=$('format').value,maxKb=parseInt($('maxKb').value,10)||0,maxBytes=maxKb*1024;let[w,h]=outputDimensions();if(w*h>40000000)throw new Error('Las dimensiones solicitadas son demasiado grandes para el navegador.');let attempt=0,encoded=null;while(attempt<8){drawImage(w,h);encoded=await encodeUnderLimit(mime,maxBytes);if(encoded.blob&&encoded.met)break;if(!maxBytes||mime==='image/png')break;w=Math.max(1,Math.floor(w*.9));h=Math.max(1,Math.floor(h*.9));attempt++}if(!encoded||!encoded.blob)throw new Error('El navegador no pudo generar el archivo.');if(maxBytes&&encoded.blob.size>maxBytes)throw new Error(mime==='image/png'?'PNG no permite ajustar la calidad. Prueba JPG o WebP para alcanzar ese peso.':'No fue posible alcanzar ese peso con estas dimensiones. Prueba dimensiones menores.');downloadUrl=URL.createObjectURL(encoded.blob);const ext=mimeExt(mime),base=sourceFile.name.replace(/\.[^.]+$/,'');$('downloadButton').href=downloadUrl;$('downloadButton').download=`${base}-filefit.${ext}`;$('beforeSize').textContent=fmtBytes(sourceFile.size);$('beforeDims').textContent=`${sourceImage.naturalWidth} × ${sourceImage.naturalHeight} px`;$('afterSize').textContent=fmtBytes(encoded.blob.size);$('afterDims').textContent=`${w} × ${h} px`;const checks=[`Formato: ${ext.toUpperCase()}`];if(maxKb)checks.push(`Peso: ${fmtBytes(encoded.blob.size)} ≤ ${maxKb} KB`);if($('width').value||$('height').value)checks.push(`Dimensiones finales: ${w} × ${h} px`);if(encoded.quality)checks.push(`Calidad elegida automáticamente: ${Math.round(encoded.quality*100)}%`);checks.push('Procesado localmente en tu dispositivo');$('checks').innerHTML=checks.map(x=>`<li>${x}</li>`).join('');result.classList.remove('hidden');setStatus('');result.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(err){setStatus(err.message||'Ocurrió un error al procesar la imagen.',true)}finally{fitButton.disabled=false;$('buttonText').textContent='Arreglar mi archivo'}}
fitButton.addEventListener('click',fit);$('resetButton').addEventListener('click',()=>{sourceFile=null;sourceImage=null;fileInput.value='';filePanel.classList.add('hidden');dropzone.classList.remove('hidden');fitButton.disabled=true;$('cropControls').classList.add('hidden');resetResult();setStatus('');window.scrollTo({top:0,behavior:'smooth'})});window.addEventListener('beforeunload',()=>{if(sourceUrl)URL.revokeObjectURL(sourceUrl);if(downloadUrl)URL.revokeObjectURL(downloadUrl)});